from flask import redirect, url_for

def previous_page(current_route):
  idx = page_flow.index(current_route)
  return page_flow[idx - 1]

# last updated routes & order 08/08/23
page_flow = (
'/',
'/fatigue',
'/minimum',
'/unrefreshed',
'/remember',
'/screener_dx',
'/short_form/soreness',
'/short_form/attention',
'/short_form/musclepain',
'/short_form/bloating',
'/short_form/bowel',
'/short_form/unsteady',
'/short_form/cold_limbs',
'/short_form/hot_cold',
'/short_form/flu',
'/short_form/smells',
'/short_form/reduction',
'/short_form/short_form_dx',
'/viral',
'/heavy',
'/mentally',
'/drained',
'/nap',
'/falling',
'/staying',
'/early',
'/allday',
'/jointpain',
'/eyepain',
'/chestpain',
'/stomach',
'/headaches',
'/twitches',
'/weakness',
'/noise',
'/lights',
'/word',
'/understand',
'/focus',
'/vision',
'/depth',
'/slowness',
'/absent',
'/bladder',
'/nausea',
'/shortness',
'/dizzy',
'/heart',
'/weight',
'/appetite',
'/sweating',
'/night',
'/chills',
'/hitemp',
'/lotemp',
'/alcohol',
'/throat',
'/lymphnodes',
'/fever',
'/intolerant',
'/dsq_dx',
'/about',
'/aboutmecfs'
)
