name: Create diagram
on: push

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
      - name: Update diagram
        uses: githubocto/repo-visualizer
        with:
          excluded_paths: "ignore,.github"